# docker-compose.yml
version: "3"
services:
  expo:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - npm-cache:/root/.npm
    environment:
      - ADB_IP=192.168.0.185
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.185
      - BROWSER=safari
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    command: npm start

volumes:
  npm-cache:
    external: false
